// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/hr/hr.proto

package go_micro_srv_hr

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EmptyMessage struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyMessage) Reset()         { *m = EmptyMessage{} }
func (m *EmptyMessage) String() string { return proto.CompactTextString(m) }
func (*EmptyMessage) ProtoMessage()    {}
func (*EmptyMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_b524aaa8c6a83ab0, []int{0}
}

func (m *EmptyMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyMessage.Unmarshal(m, b)
}
func (m *EmptyMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyMessage.Marshal(b, m, deterministic)
}
func (m *EmptyMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyMessage.Merge(m, src)
}
func (m *EmptyMessage) XXX_Size() int {
	return xxx_messageInfo_EmptyMessage.Size(m)
}
func (m *EmptyMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyMessage.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyMessage proto.InternalMessageInfo

// Departments
type CreateDepartmentRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateDepartmentRequest) Reset()         { *m = CreateDepartmentRequest{} }
func (m *CreateDepartmentRequest) String() string { return proto.CompactTextString(m) }
func (*CreateDepartmentRequest) ProtoMessage()    {}
func (*CreateDepartmentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b524aaa8c6a83ab0, []int{1}
}

func (m *CreateDepartmentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDepartmentRequest.Unmarshal(m, b)
}
func (m *CreateDepartmentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDepartmentRequest.Marshal(b, m, deterministic)
}
func (m *CreateDepartmentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDepartmentRequest.Merge(m, src)
}
func (m *CreateDepartmentRequest) XXX_Size() int {
	return xxx_messageInfo_CreateDepartmentRequest.Size(m)
}
func (m *CreateDepartmentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDepartmentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDepartmentRequest proto.InternalMessageInfo

func (m *CreateDepartmentRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateDepartmentResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateDepartmentResponse) Reset()         { *m = CreateDepartmentResponse{} }
func (m *CreateDepartmentResponse) String() string { return proto.CompactTextString(m) }
func (*CreateDepartmentResponse) ProtoMessage()    {}
func (*CreateDepartmentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b524aaa8c6a83ab0, []int{2}
}

func (m *CreateDepartmentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDepartmentResponse.Unmarshal(m, b)
}
func (m *CreateDepartmentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDepartmentResponse.Marshal(b, m, deterministic)
}
func (m *CreateDepartmentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDepartmentResponse.Merge(m, src)
}
func (m *CreateDepartmentResponse) XXX_Size() int {
	return xxx_messageInfo_CreateDepartmentResponse.Size(m)
}
func (m *CreateDepartmentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDepartmentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDepartmentResponse proto.InternalMessageInfo

func (m *CreateDepartmentResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DepartmentsRequest struct {
	SkipCount            int32    `protobuf:"varint,1,opt,name=skip_count,json=skipCount,proto3" json:"skip_count,omitempty"`
	MaxResultCount       int32    `protobuf:"varint,2,opt,name=max_result_count,json=maxResultCount,proto3" json:"max_result_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DepartmentsRequest) Reset()         { *m = DepartmentsRequest{} }
func (m *DepartmentsRequest) String() string { return proto.CompactTextString(m) }
func (*DepartmentsRequest) ProtoMessage()    {}
func (*DepartmentsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b524aaa8c6a83ab0, []int{3}
}

func (m *DepartmentsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DepartmentsRequest.Unmarshal(m, b)
}
func (m *DepartmentsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DepartmentsRequest.Marshal(b, m, deterministic)
}
func (m *DepartmentsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DepartmentsRequest.Merge(m, src)
}
func (m *DepartmentsRequest) XXX_Size() int {
	return xxx_messageInfo_DepartmentsRequest.Size(m)
}
func (m *DepartmentsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DepartmentsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DepartmentsRequest proto.InternalMessageInfo

func (m *DepartmentsRequest) GetSkipCount() int32 {
	if m != nil {
		return m.SkipCount
	}
	return 0
}

func (m *DepartmentsRequest) GetMaxResultCount() int32 {
	if m != nil {
		return m.MaxResultCount
	}
	return 0
}

type DepartmentsResponse struct {
	TotalCount           int64         `protobuf:"varint,1,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Departments          []*Department `protobuf:"bytes,2,rep,name=departments,proto3" json:"departments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *DepartmentsResponse) Reset()         { *m = DepartmentsResponse{} }
func (m *DepartmentsResponse) String() string { return proto.CompactTextString(m) }
func (*DepartmentsResponse) ProtoMessage()    {}
func (*DepartmentsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b524aaa8c6a83ab0, []int{4}
}

func (m *DepartmentsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DepartmentsResponse.Unmarshal(m, b)
}
func (m *DepartmentsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DepartmentsResponse.Marshal(b, m, deterministic)
}
func (m *DepartmentsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DepartmentsResponse.Merge(m, src)
}
func (m *DepartmentsResponse) XXX_Size() int {
	return xxx_messageInfo_DepartmentsResponse.Size(m)
}
func (m *DepartmentsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DepartmentsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DepartmentsResponse proto.InternalMessageInfo

func (m *DepartmentsResponse) GetTotalCount() int64 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func (m *DepartmentsResponse) GetDepartments() []*Department {
	if m != nil {
		return m.Departments
	}
	return nil
}

type Department struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Department) Reset()         { *m = Department{} }
func (m *Department) String() string { return proto.CompactTextString(m) }
func (*Department) ProtoMessage()    {}
func (*Department) Descriptor() ([]byte, []int) {
	return fileDescriptor_b524aaa8c6a83ab0, []int{5}
}

func (m *Department) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Department.Unmarshal(m, b)
}
func (m *Department) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Department.Marshal(b, m, deterministic)
}
func (m *Department) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Department.Merge(m, src)
}
func (m *Department) XXX_Size() int {
	return xxx_messageInfo_Department.Size(m)
}
func (m *Department) XXX_DiscardUnknown() {
	xxx_messageInfo_Department.DiscardUnknown(m)
}

var xxx_messageInfo_Department proto.InternalMessageInfo

func (m *Department) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Department) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UpdateDepartmentRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateDepartmentRequest) Reset()         { *m = UpdateDepartmentRequest{} }
func (m *UpdateDepartmentRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateDepartmentRequest) ProtoMessage()    {}
func (*UpdateDepartmentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b524aaa8c6a83ab0, []int{6}
}

func (m *UpdateDepartmentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateDepartmentRequest.Unmarshal(m, b)
}
func (m *UpdateDepartmentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateDepartmentRequest.Marshal(b, m, deterministic)
}
func (m *UpdateDepartmentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateDepartmentRequest.Merge(m, src)
}
func (m *UpdateDepartmentRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateDepartmentRequest.Size(m)
}
func (m *UpdateDepartmentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateDepartmentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateDepartmentRequest proto.InternalMessageInfo

func (m *UpdateDepartmentRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateDepartmentRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DeleteDepartmentRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteDepartmentRequest) Reset()         { *m = DeleteDepartmentRequest{} }
func (m *DeleteDepartmentRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteDepartmentRequest) ProtoMessage()    {}
func (*DeleteDepartmentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b524aaa8c6a83ab0, []int{7}
}

func (m *DeleteDepartmentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteDepartmentRequest.Unmarshal(m, b)
}
func (m *DeleteDepartmentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteDepartmentRequest.Marshal(b, m, deterministic)
}
func (m *DeleteDepartmentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteDepartmentRequest.Merge(m, src)
}
func (m *DeleteDepartmentRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteDepartmentRequest.Size(m)
}
func (m *DeleteDepartmentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteDepartmentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteDepartmentRequest proto.InternalMessageInfo

func (m *DeleteDepartmentRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// Employee Type
type CreateEmployeeTypeRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DepartmentId         string   `protobuf:"bytes,2,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	CanLogin             bool     `protobuf:"varint,3,opt,name=can_login,json=canLogin,proto3" json:"can_login,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateEmployeeTypeRequest) Reset()         { *m = CreateEmployeeTypeRequest{} }
func (m *CreateEmployeeTypeRequest) String() string { return proto.CompactTextString(m) }
func (*CreateEmployeeTypeRequest) ProtoMessage()    {}
func (*CreateEmployeeTypeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b524aaa8c6a83ab0, []int{8}
}

func (m *CreateEmployeeTypeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEmployeeTypeRequest.Unmarshal(m, b)
}
func (m *CreateEmployeeTypeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEmployeeTypeRequest.Marshal(b, m, deterministic)
}
func (m *CreateEmployeeTypeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEmployeeTypeRequest.Merge(m, src)
}
func (m *CreateEmployeeTypeRequest) XXX_Size() int {
	return xxx_messageInfo_CreateEmployeeTypeRequest.Size(m)
}
func (m *CreateEmployeeTypeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEmployeeTypeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEmployeeTypeRequest proto.InternalMessageInfo

func (m *CreateEmployeeTypeRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateEmployeeTypeRequest) GetDepartmentId() string {
	if m != nil {
		return m.DepartmentId
	}
	return ""
}

func (m *CreateEmployeeTypeRequest) GetCanLogin() bool {
	if m != nil {
		return m.CanLogin
	}
	return false
}

type CreateEmployeeTypeResponse struct {
	EmployeeTypeId       string   `protobuf:"bytes,1,opt,name=employee_type_id,json=employeeTypeId,proto3" json:"employee_type_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateEmployeeTypeResponse) Reset()         { *m = CreateEmployeeTypeResponse{} }
func (m *CreateEmployeeTypeResponse) String() string { return proto.CompactTextString(m) }
func (*CreateEmployeeTypeResponse) ProtoMessage()    {}
func (*CreateEmployeeTypeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b524aaa8c6a83ab0, []int{9}
}

func (m *CreateEmployeeTypeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEmployeeTypeResponse.Unmarshal(m, b)
}
func (m *CreateEmployeeTypeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEmployeeTypeResponse.Marshal(b, m, deterministic)
}
func (m *CreateEmployeeTypeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEmployeeTypeResponse.Merge(m, src)
}
func (m *CreateEmployeeTypeResponse) XXX_Size() int {
	return xxx_messageInfo_CreateEmployeeTypeResponse.Size(m)
}
func (m *CreateEmployeeTypeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEmployeeTypeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEmployeeTypeResponse proto.InternalMessageInfo

func (m *CreateEmployeeTypeResponse) GetEmployeeTypeId() string {
	if m != nil {
		return m.EmployeeTypeId
	}
	return ""
}

type EmployeeTypesRequest struct {
	DepartmentId         string   `protobuf:"bytes,1,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	SkipCount            int32    `protobuf:"varint,2,opt,name=skip_count,json=skipCount,proto3" json:"skip_count,omitempty"`
	MaxResultCount       int32    `protobuf:"varint,3,opt,name=max_result_count,json=maxResultCount,proto3" json:"max_result_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmployeeTypesRequest) Reset()         { *m = EmployeeTypesRequest{} }
func (m *EmployeeTypesRequest) String() string { return proto.CompactTextString(m) }
func (*EmployeeTypesRequest) ProtoMessage()    {}
func (*EmployeeTypesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b524aaa8c6a83ab0, []int{10}
}

func (m *EmployeeTypesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmployeeTypesRequest.Unmarshal(m, b)
}
func (m *EmployeeTypesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmployeeTypesRequest.Marshal(b, m, deterministic)
}
func (m *EmployeeTypesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmployeeTypesRequest.Merge(m, src)
}
func (m *EmployeeTypesRequest) XXX_Size() int {
	return xxx_messageInfo_EmployeeTypesRequest.Size(m)
}
func (m *EmployeeTypesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmployeeTypesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmployeeTypesRequest proto.InternalMessageInfo

func (m *EmployeeTypesRequest) GetDepartmentId() string {
	if m != nil {
		return m.DepartmentId
	}
	return ""
}

func (m *EmployeeTypesRequest) GetSkipCount() int32 {
	if m != nil {
		return m.SkipCount
	}
	return 0
}

func (m *EmployeeTypesRequest) GetMaxResultCount() int32 {
	if m != nil {
		return m.MaxResultCount
	}
	return 0
}

type EmployeeTypesResponse struct {
	TotalCount           int64           `protobuf:"varint,1,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	EmployeeTypes        []*EmployeeType `protobuf:"bytes,2,rep,name=employee_types,json=employeeTypes,proto3" json:"employee_types,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *EmployeeTypesResponse) Reset()         { *m = EmployeeTypesResponse{} }
func (m *EmployeeTypesResponse) String() string { return proto.CompactTextString(m) }
func (*EmployeeTypesResponse) ProtoMessage()    {}
func (*EmployeeTypesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b524aaa8c6a83ab0, []int{11}
}

func (m *EmployeeTypesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmployeeTypesResponse.Unmarshal(m, b)
}
func (m *EmployeeTypesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmployeeTypesResponse.Marshal(b, m, deterministic)
}
func (m *EmployeeTypesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmployeeTypesResponse.Merge(m, src)
}
func (m *EmployeeTypesResponse) XXX_Size() int {
	return xxx_messageInfo_EmployeeTypesResponse.Size(m)
}
func (m *EmployeeTypesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EmployeeTypesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EmployeeTypesResponse proto.InternalMessageInfo

func (m *EmployeeTypesResponse) GetTotalCount() int64 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func (m *EmployeeTypesResponse) GetEmployeeTypes() []*EmployeeType {
	if m != nil {
		return m.EmployeeTypes
	}
	return nil
}

type EmployeeType struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Department           string   `protobuf:"bytes,3,opt,name=department,proto3" json:"department,omitempty"`
	DepartmentId         string   `protobuf:"bytes,4,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	CanLogin             bool     `protobuf:"varint,5,opt,name=can_login,json=canLogin,proto3" json:"can_login,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmployeeType) Reset()         { *m = EmployeeType{} }
func (m *EmployeeType) String() string { return proto.CompactTextString(m) }
func (*EmployeeType) ProtoMessage()    {}
func (*EmployeeType) Descriptor() ([]byte, []int) {
	return fileDescriptor_b524aaa8c6a83ab0, []int{12}
}

func (m *EmployeeType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmployeeType.Unmarshal(m, b)
}
func (m *EmployeeType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmployeeType.Marshal(b, m, deterministic)
}
func (m *EmployeeType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmployeeType.Merge(m, src)
}
func (m *EmployeeType) XXX_Size() int {
	return xxx_messageInfo_EmployeeType.Size(m)
}
func (m *EmployeeType) XXX_DiscardUnknown() {
	xxx_messageInfo_EmployeeType.DiscardUnknown(m)
}

var xxx_messageInfo_EmployeeType proto.InternalMessageInfo

func (m *EmployeeType) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *EmployeeType) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EmployeeType) GetDepartment() string {
	if m != nil {
		return m.Department
	}
	return ""
}

func (m *EmployeeType) GetDepartmentId() string {
	if m != nil {
		return m.DepartmentId
	}
	return ""
}

func (m *EmployeeType) GetCanLogin() bool {
	if m != nil {
		return m.CanLogin
	}
	return false
}

type UpdateEmployeeTypeRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DepartmentId         string   `protobuf:"bytes,3,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	CanLogin             bool     `protobuf:"varint,4,opt,name=can_login,json=canLogin,proto3" json:"can_login,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateEmployeeTypeRequest) Reset()         { *m = UpdateEmployeeTypeRequest{} }
func (m *UpdateEmployeeTypeRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateEmployeeTypeRequest) ProtoMessage()    {}
func (*UpdateEmployeeTypeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b524aaa8c6a83ab0, []int{13}
}

func (m *UpdateEmployeeTypeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateEmployeeTypeRequest.Unmarshal(m, b)
}
func (m *UpdateEmployeeTypeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateEmployeeTypeRequest.Marshal(b, m, deterministic)
}
func (m *UpdateEmployeeTypeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateEmployeeTypeRequest.Merge(m, src)
}
func (m *UpdateEmployeeTypeRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateEmployeeTypeRequest.Size(m)
}
func (m *UpdateEmployeeTypeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateEmployeeTypeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateEmployeeTypeRequest proto.InternalMessageInfo

func (m *UpdateEmployeeTypeRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateEmployeeTypeRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateEmployeeTypeRequest) GetDepartmentId() string {
	if m != nil {
		return m.DepartmentId
	}
	return ""
}

func (m *UpdateEmployeeTypeRequest) GetCanLogin() bool {
	if m != nil {
		return m.CanLogin
	}
	return false
}

type DeleteEmployeeTypeRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteEmployeeTypeRequest) Reset()         { *m = DeleteEmployeeTypeRequest{} }
func (m *DeleteEmployeeTypeRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteEmployeeTypeRequest) ProtoMessage()    {}
func (*DeleteEmployeeTypeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b524aaa8c6a83ab0, []int{14}
}

func (m *DeleteEmployeeTypeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteEmployeeTypeRequest.Unmarshal(m, b)
}
func (m *DeleteEmployeeTypeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteEmployeeTypeRequest.Marshal(b, m, deterministic)
}
func (m *DeleteEmployeeTypeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteEmployeeTypeRequest.Merge(m, src)
}
func (m *DeleteEmployeeTypeRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteEmployeeTypeRequest.Size(m)
}
func (m *DeleteEmployeeTypeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteEmployeeTypeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteEmployeeTypeRequest proto.InternalMessageInfo

func (m *DeleteEmployeeTypeRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// Employee
type CreateEmployeeRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DepartmentId         string   `protobuf:"bytes,2,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	EmployeeTypeId       string   `protobuf:"bytes,3,opt,name=employee_type_id,json=employeeTypeId,proto3" json:"employee_type_id,omitempty"`
	Username             string   `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	Email                string   `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,7,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateEmployeeRequest) Reset()         { *m = CreateEmployeeRequest{} }
func (m *CreateEmployeeRequest) String() string { return proto.CompactTextString(m) }
func (*CreateEmployeeRequest) ProtoMessage()    {}
func (*CreateEmployeeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b524aaa8c6a83ab0, []int{15}
}

func (m *CreateEmployeeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEmployeeRequest.Unmarshal(m, b)
}
func (m *CreateEmployeeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEmployeeRequest.Marshal(b, m, deterministic)
}
func (m *CreateEmployeeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEmployeeRequest.Merge(m, src)
}
func (m *CreateEmployeeRequest) XXX_Size() int {
	return xxx_messageInfo_CreateEmployeeRequest.Size(m)
}
func (m *CreateEmployeeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEmployeeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEmployeeRequest proto.InternalMessageInfo

func (m *CreateEmployeeRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateEmployeeRequest) GetDepartmentId() string {
	if m != nil {
		return m.DepartmentId
	}
	return ""
}

func (m *CreateEmployeeRequest) GetEmployeeTypeId() string {
	if m != nil {
		return m.EmployeeTypeId
	}
	return ""
}

func (m *CreateEmployeeRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CreateEmployeeRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateEmployeeRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateEmployeeRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

type CreateEmployeeResponse struct {
	EmployeeId           string   `protobuf:"bytes,1,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateEmployeeResponse) Reset()         { *m = CreateEmployeeResponse{} }
func (m *CreateEmployeeResponse) String() string { return proto.CompactTextString(m) }
func (*CreateEmployeeResponse) ProtoMessage()    {}
func (*CreateEmployeeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b524aaa8c6a83ab0, []int{16}
}

func (m *CreateEmployeeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEmployeeResponse.Unmarshal(m, b)
}
func (m *CreateEmployeeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEmployeeResponse.Marshal(b, m, deterministic)
}
func (m *CreateEmployeeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEmployeeResponse.Merge(m, src)
}
func (m *CreateEmployeeResponse) XXX_Size() int {
	return xxx_messageInfo_CreateEmployeeResponse.Size(m)
}
func (m *CreateEmployeeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEmployeeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEmployeeResponse proto.InternalMessageInfo

func (m *CreateEmployeeResponse) GetEmployeeId() string {
	if m != nil {
		return m.EmployeeId
	}
	return ""
}

type EmployeesRequest struct {
	DepartmentId         string   `protobuf:"bytes,1,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	EmployeeTypeId       string   `protobuf:"bytes,2,opt,name=employee_type_id,json=employeeTypeId,proto3" json:"employee_type_id,omitempty"`
	SkipCount            int32    `protobuf:"varint,3,opt,name=skip_count,json=skipCount,proto3" json:"skip_count,omitempty"`
	MaxResultCount       int32    `protobuf:"varint,4,opt,name=max_result_count,json=maxResultCount,proto3" json:"max_result_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmployeesRequest) Reset()         { *m = EmployeesRequest{} }
func (m *EmployeesRequest) String() string { return proto.CompactTextString(m) }
func (*EmployeesRequest) ProtoMessage()    {}
func (*EmployeesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b524aaa8c6a83ab0, []int{17}
}

func (m *EmployeesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmployeesRequest.Unmarshal(m, b)
}
func (m *EmployeesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmployeesRequest.Marshal(b, m, deterministic)
}
func (m *EmployeesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmployeesRequest.Merge(m, src)
}
func (m *EmployeesRequest) XXX_Size() int {
	return xxx_messageInfo_EmployeesRequest.Size(m)
}
func (m *EmployeesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmployeesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmployeesRequest proto.InternalMessageInfo

func (m *EmployeesRequest) GetDepartmentId() string {
	if m != nil {
		return m.DepartmentId
	}
	return ""
}

func (m *EmployeesRequest) GetEmployeeTypeId() string {
	if m != nil {
		return m.EmployeeTypeId
	}
	return ""
}

func (m *EmployeesRequest) GetSkipCount() int32 {
	if m != nil {
		return m.SkipCount
	}
	return 0
}

func (m *EmployeesRequest) GetMaxResultCount() int32 {
	if m != nil {
		return m.MaxResultCount
	}
	return 0
}

type EmployeesResponse struct {
	TotalCount           int64       `protobuf:"varint,1,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Employees            []*Employee `protobuf:"bytes,2,rep,name=employees,proto3" json:"employees,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *EmployeesResponse) Reset()         { *m = EmployeesResponse{} }
func (m *EmployeesResponse) String() string { return proto.CompactTextString(m) }
func (*EmployeesResponse) ProtoMessage()    {}
func (*EmployeesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b524aaa8c6a83ab0, []int{18}
}

func (m *EmployeesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmployeesResponse.Unmarshal(m, b)
}
func (m *EmployeesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmployeesResponse.Marshal(b, m, deterministic)
}
func (m *EmployeesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmployeesResponse.Merge(m, src)
}
func (m *EmployeesResponse) XXX_Size() int {
	return xxx_messageInfo_EmployeesResponse.Size(m)
}
func (m *EmployeesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EmployeesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EmployeesResponse proto.InternalMessageInfo

func (m *EmployeesResponse) GetTotalCount() int64 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func (m *EmployeesResponse) GetEmployees() []*Employee {
	if m != nil {
		return m.Employees
	}
	return nil
}

type Employee struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DepartmentId         string   `protobuf:"bytes,3,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	EmployeeTypeId       string   `protobuf:"bytes,4,opt,name=employee_type_id,json=employeeTypeId,proto3" json:"employee_type_id,omitempty"`
	Department           string   `protobuf:"bytes,5,opt,name=department,proto3" json:"department,omitempty"`
	EmployeeType         string   `protobuf:"bytes,6,opt,name=employee_type,json=employeeType,proto3" json:"employee_type,omitempty"`
	Username             string   `protobuf:"bytes,7,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,8,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,9,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Employee) Reset()         { *m = Employee{} }
func (m *Employee) String() string { return proto.CompactTextString(m) }
func (*Employee) ProtoMessage()    {}
func (*Employee) Descriptor() ([]byte, []int) {
	return fileDescriptor_b524aaa8c6a83ab0, []int{19}
}

func (m *Employee) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Employee.Unmarshal(m, b)
}
func (m *Employee) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Employee.Marshal(b, m, deterministic)
}
func (m *Employee) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Employee.Merge(m, src)
}
func (m *Employee) XXX_Size() int {
	return xxx_messageInfo_Employee.Size(m)
}
func (m *Employee) XXX_DiscardUnknown() {
	xxx_messageInfo_Employee.DiscardUnknown(m)
}

var xxx_messageInfo_Employee proto.InternalMessageInfo

func (m *Employee) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Employee) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Employee) GetDepartmentId() string {
	if m != nil {
		return m.DepartmentId
	}
	return ""
}

func (m *Employee) GetEmployeeTypeId() string {
	if m != nil {
		return m.EmployeeTypeId
	}
	return ""
}

func (m *Employee) GetDepartment() string {
	if m != nil {
		return m.Department
	}
	return ""
}

func (m *Employee) GetEmployeeType() string {
	if m != nil {
		return m.EmployeeType
	}
	return ""
}

func (m *Employee) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Employee) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Employee) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

type UpdateEmployeeRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DepartmentId         string   `protobuf:"bytes,3,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	EmployeeTypeId       string   `protobuf:"bytes,4,opt,name=employee_type_id,json=employeeTypeId,proto3" json:"employee_type_id,omitempty"`
	Username             string   `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,7,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateEmployeeRequest) Reset()         { *m = UpdateEmployeeRequest{} }
func (m *UpdateEmployeeRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateEmployeeRequest) ProtoMessage()    {}
func (*UpdateEmployeeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b524aaa8c6a83ab0, []int{20}
}

func (m *UpdateEmployeeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateEmployeeRequest.Unmarshal(m, b)
}
func (m *UpdateEmployeeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateEmployeeRequest.Marshal(b, m, deterministic)
}
func (m *UpdateEmployeeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateEmployeeRequest.Merge(m, src)
}
func (m *UpdateEmployeeRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateEmployeeRequest.Size(m)
}
func (m *UpdateEmployeeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateEmployeeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateEmployeeRequest proto.InternalMessageInfo

func (m *UpdateEmployeeRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateEmployeeRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateEmployeeRequest) GetDepartmentId() string {
	if m != nil {
		return m.DepartmentId
	}
	return ""
}

func (m *UpdateEmployeeRequest) GetEmployeeTypeId() string {
	if m != nil {
		return m.EmployeeTypeId
	}
	return ""
}

func (m *UpdateEmployeeRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UpdateEmployeeRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UpdateEmployeeRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

type DeleteEmployeeRequest struct {
	EmployeeId           string   `protobuf:"bytes,1,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteEmployeeRequest) Reset()         { *m = DeleteEmployeeRequest{} }
func (m *DeleteEmployeeRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteEmployeeRequest) ProtoMessage()    {}
func (*DeleteEmployeeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b524aaa8c6a83ab0, []int{21}
}

func (m *DeleteEmployeeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteEmployeeRequest.Unmarshal(m, b)
}
func (m *DeleteEmployeeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteEmployeeRequest.Marshal(b, m, deterministic)
}
func (m *DeleteEmployeeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteEmployeeRequest.Merge(m, src)
}
func (m *DeleteEmployeeRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteEmployeeRequest.Size(m)
}
func (m *DeleteEmployeeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteEmployeeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteEmployeeRequest proto.InternalMessageInfo

func (m *DeleteEmployeeRequest) GetEmployeeId() string {
	if m != nil {
		return m.EmployeeId
	}
	return ""
}

func init() {
	proto.RegisterType((*EmptyMessage)(nil), "go.micro.srv.hr.EmptyMessage")
	proto.RegisterType((*CreateDepartmentRequest)(nil), "go.micro.srv.hr.CreateDepartmentRequest")
	proto.RegisterType((*CreateDepartmentResponse)(nil), "go.micro.srv.hr.CreateDepartmentResponse")
	proto.RegisterType((*DepartmentsRequest)(nil), "go.micro.srv.hr.DepartmentsRequest")
	proto.RegisterType((*DepartmentsResponse)(nil), "go.micro.srv.hr.DepartmentsResponse")
	proto.RegisterType((*Department)(nil), "go.micro.srv.hr.Department")
	proto.RegisterType((*UpdateDepartmentRequest)(nil), "go.micro.srv.hr.UpdateDepartmentRequest")
	proto.RegisterType((*DeleteDepartmentRequest)(nil), "go.micro.srv.hr.DeleteDepartmentRequest")
	proto.RegisterType((*CreateEmployeeTypeRequest)(nil), "go.micro.srv.hr.CreateEmployeeTypeRequest")
	proto.RegisterType((*CreateEmployeeTypeResponse)(nil), "go.micro.srv.hr.CreateEmployeeTypeResponse")
	proto.RegisterType((*EmployeeTypesRequest)(nil), "go.micro.srv.hr.EmployeeTypesRequest")
	proto.RegisterType((*EmployeeTypesResponse)(nil), "go.micro.srv.hr.EmployeeTypesResponse")
	proto.RegisterType((*EmployeeType)(nil), "go.micro.srv.hr.EmployeeType")
	proto.RegisterType((*UpdateEmployeeTypeRequest)(nil), "go.micro.srv.hr.UpdateEmployeeTypeRequest")
	proto.RegisterType((*DeleteEmployeeTypeRequest)(nil), "go.micro.srv.hr.DeleteEmployeeTypeRequest")
	proto.RegisterType((*CreateEmployeeRequest)(nil), "go.micro.srv.hr.CreateEmployeeRequest")
	proto.RegisterType((*CreateEmployeeResponse)(nil), "go.micro.srv.hr.CreateEmployeeResponse")
	proto.RegisterType((*EmployeesRequest)(nil), "go.micro.srv.hr.EmployeesRequest")
	proto.RegisterType((*EmployeesResponse)(nil), "go.micro.srv.hr.EmployeesResponse")
	proto.RegisterType((*Employee)(nil), "go.micro.srv.hr.Employee")
	proto.RegisterType((*UpdateEmployeeRequest)(nil), "go.micro.srv.hr.UpdateEmployeeRequest")
	proto.RegisterType((*DeleteEmployeeRequest)(nil), "go.micro.srv.hr.DeleteEmployeeRequest")
}

func init() { proto.RegisterFile("proto/hr/hr.proto", fileDescriptor_b524aaa8c6a83ab0) }

var fileDescriptor_b524aaa8c6a83ab0 = []byte{
	// 876 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0xdd, 0x4e, 0xdb, 0x48,
	0x14, 0x5e, 0x3b, 0x09, 0xc4, 0x27, 0xc1, 0x1b, 0x66, 0xc9, 0x92, 0x04, 0xb1, 0x0b, 0xc3, 0x2e,
	0x1b, 0x40, 0x1b, 0x56, 0xec, 0xc5, 0x6e, 0x2f, 0xb8, 0x02, 0xaa, 0x22, 0xb5, 0xbd, 0xb0, 0xe8,
	0x05, 0x95, 0x50, 0x6a, 0xe2, 0x11, 0xb1, 0x1a, 0xff, 0x60, 0x3b, 0x2d, 0xb9, 0xa9, 0x54, 0xa9,
	0x6f, 0xd0, 0x4a, 0x7d, 0x87, 0xbe, 0x54, 0x1f, 0xa0, 0x2f, 0x51, 0x65, 0x12, 0x8f, 0x3d, 0xf6,
	0x38, 0x36, 0x2a, 0x77, 0xf1, 0xf1, 0xe7, 0xf3, 0xf3, 0xcd, 0x77, 0xe6, 0x9c, 0xc0, 0xaa, 0xeb,
	0x39, 0x81, 0x73, 0x38, 0xf4, 0x0e, 0x87, 0x5e, 0x8f, 0xfe, 0x46, 0x3f, 0xdf, 0x38, 0x3d, 0xcb,
	0x1c, 0x78, 0x4e, 0xcf, 0xf7, 0xde, 0xf4, 0x86, 0x1e, 0x56, 0xa1, 0x7e, 0x66, 0xb9, 0xc1, 0xe4,
	0x19, 0xf1, 0x7d, 0xfd, 0x86, 0xe0, 0xbf, 0x61, 0xfd, 0xc4, 0x23, 0x7a, 0x40, 0x4e, 0x89, 0xab,
	0x7b, 0x81, 0x45, 0xec, 0x40, 0x23, 0xb7, 0x63, 0xe2, 0x07, 0x08, 0x41, 0xd9, 0xd6, 0x2d, 0xd2,
	0x92, 0xb6, 0xa4, 0xae, 0xa2, 0xd1, 0xdf, 0x78, 0x1f, 0x5a, 0x69, 0xb8, 0xef, 0x3a, 0xb6, 0x4f,
	0x90, 0x0a, 0xb2, 0x69, 0xcc, 0xd1, 0xb2, 0x69, 0xe0, 0x2b, 0x40, 0x11, 0xca, 0x0f, 0xbd, 0x6e,
	0x02, 0xf8, 0xaf, 0x4d, 0xb7, 0x3f, 0x70, 0xc6, 0x76, 0x40, 0xd1, 0x15, 0x4d, 0x99, 0x5a, 0x4e,
	0xa6, 0x06, 0xd4, 0x85, 0x86, 0xa5, 0xdf, 0xf5, 0x3d, 0xe2, 0x8f, 0x47, 0xc1, 0x1c, 0x24, 0x53,
	0x90, 0x6a, 0xe9, 0x77, 0x1a, 0x35, 0x53, 0x24, 0x1e, 0xc3, 0x2f, 0x9c, 0xfb, 0x79, 0x16, 0xbf,
	0x43, 0x2d, 0x70, 0x02, 0x7d, 0x14, 0x0b, 0x50, 0xd2, 0x80, 0x9a, 0x66, 0x11, 0x8e, 0xa1, 0x66,
	0x44, 0xdf, 0xb5, 0xe4, 0xad, 0x52, 0xb7, 0x76, 0xb4, 0xd1, 0x4b, 0x10, 0xd5, 0x8b, 0x15, 0x18,
	0xc7, 0xe3, 0x7f, 0x00, 0xa2, 0x57, 0xc9, 0x9a, 0x19, 0x67, 0x72, 0x8c, 0xb3, 0x63, 0x58, 0x7f,
	0xe1, 0x1a, 0x42, 0x8a, 0x8b, 0x7c, 0xbe, 0x07, 0xeb, 0xa7, 0x64, 0x44, 0x0a, 0x7c, 0x8e, 0x6f,
	0xa1, 0x3d, 0x3b, 0x9d, 0x33, 0xcb, 0x1d, 0x39, 0x13, 0x42, 0x2e, 0x26, 0x2e, 0x59, 0x70, 0x9c,
	0x68, 0x07, 0x56, 0xa2, 0xda, 0xfa, 0xa6, 0x31, 0x0f, 0x5c, 0x8f, 0x8c, 0xe7, 0x06, 0xda, 0x00,
	0x65, 0xa0, 0xdb, 0xfd, 0x91, 0x73, 0x63, 0xda, 0xad, 0xd2, 0x96, 0xd4, 0xad, 0x6a, 0xd5, 0x81,
	0x6e, 0x3f, 0x9d, 0x3e, 0xe3, 0xc7, 0xd0, 0x11, 0x85, 0x9c, 0x1f, 0x46, 0x17, 0x1a, 0x64, 0x6e,
	0xef, 0x07, 0x13, 0x97, 0xf4, 0x59, 0xba, 0x2a, 0x89, 0xe1, 0xcf, 0x0d, 0xfc, 0x41, 0x82, 0xb5,
	0xb8, 0x0b, 0xa6, 0x97, 0x54, 0x8a, 0x92, 0x20, 0x45, 0x5e, 0x54, 0x72, 0x11, 0x51, 0x95, 0x84,
	0xa2, 0x7a, 0x07, 0xcd, 0x44, 0x16, 0x45, 0x65, 0x75, 0x0a, 0x2a, 0x57, 0x6a, 0xa8, 0xac, 0xcd,
	0x94, 0xb2, 0x38, 0xa6, 0x56, 0xe2, 0x3c, 0xf8, 0xf8, 0x93, 0x44, 0xfb, 0x93, 0x59, 0x8a, 0x28,
	0x04, 0xfd, 0x06, 0x10, 0xb1, 0x41, 0x0b, 0x53, 0xb4, 0x98, 0x25, 0x4d, 0x61, 0x39, 0xef, 0x94,
	0x2b, 0x89, 0x53, 0x7e, 0x2f, 0x41, 0x7b, 0xa6, 0x61, 0x91, 0xb2, 0x8a, 0xe4, 0x98, 0xca, 0xa1,
	0x94, 0x97, 0x43, 0x39, 0x91, 0xc3, 0x01, 0xb4, 0x67, 0x7d, 0x50, 0x20, 0x05, 0xfc, 0x4d, 0x82,
	0x26, 0xaf, 0xcb, 0x1f, 0x6e, 0x03, 0x91, 0x96, 0x4b, 0x22, 0x2d, 0xa3, 0x0e, 0x54, 0xc7, 0x3e,
	0xf1, 0x68, 0x98, 0x19, 0xd5, 0xec, 0x79, 0xfa, 0xce, 0xd5, 0x7d, 0xff, 0xad, 0xe3, 0x19, 0x94,
	0x65, 0x45, 0x63, 0xcf, 0x68, 0x0d, 0x2a, 0xc4, 0xd2, 0xcd, 0x51, 0x6b, 0x89, 0xbe, 0x98, 0x3d,
	0xa0, 0x6d, 0xa8, 0xbb, 0x43, 0xc7, 0x26, 0x7d, 0x7b, 0x6c, 0x5d, 0x13, 0xaf, 0xb5, 0x4c, 0x5f,
	0xd6, 0xa8, 0xed, 0x39, 0x35, 0xe1, 0x47, 0xf0, 0x6b, 0xb2, 0xd8, 0x48, 0xb6, 0x2c, 0x69, 0x46,
	0x10, 0x84, 0xa6, 0x73, 0x03, 0x7f, 0x91, 0xa0, 0x11, 0x7e, 0x75, 0xbf, 0x9e, 0x13, 0xf1, 0x21,
	0x0b, 0xf9, 0xe0, 0xbb, 0xb3, 0x54, 0xa4, 0x3b, 0xcb, 0xc2, 0xee, 0xb4, 0x60, 0x35, 0x96, 0x6b,
	0xd1, 0xce, 0xfc, 0x0f, 0x94, 0x30, 0xa1, 0xb0, 0x29, 0xdb, 0x99, 0x4d, 0xa9, 0x45, 0x58, 0xfc,
	0x59, 0x86, 0x6a, 0x68, 0x7f, 0x38, 0x91, 0x8b, 0x78, 0x2b, 0x0b, 0x79, 0xe3, 0xfb, 0xba, 0x22,
	0xea, 0x6b, 0xce, 0xd3, 0x5c, 0x37, 0xf5, 0xb8, 0x1b, 0x4e, 0x8c, 0xcb, 0x09, 0x31, 0x32, 0xc1,
	0x55, 0x17, 0x09, 0x4e, 0x49, 0x0b, 0xee, 0xab, 0x04, 0x4d, 0xfe, 0x3e, 0x78, 0xf0, 0xbb, 0xa0,
	0x38, 0x4d, 0xf1, 0x0a, 0x2b, 0x59, 0x15, 0xde, 0xb7, 0xa5, 0xfe, 0x87, 0x26, 0x7f, 0xdb, 0x84,
	0x05, 0xe6, 0x75, 0xd4, 0xd1, 0x47, 0x05, 0xe4, 0x27, 0x1e, 0x32, 0xa1, 0x91, 0xdc, 0x94, 0x50,
	0x37, 0x25, 0xbb, 0x8c, 0xdd, 0xab, 0xb3, 0x57, 0x00, 0x39, 0xd3, 0x3f, 0xfe, 0x09, 0xbd, 0x84,
	0x5a, 0x6c, 0x13, 0x42, 0x3b, 0x0b, 0x76, 0x99, 0xb0, 0xc5, 0x3b, 0x7f, 0x2c, 0x06, 0x31, 0xdf,
	0x57, 0xd0, 0x48, 0x2e, 0x2f, 0x82, 0x32, 0x32, 0xf6, 0x9b, 0x8e, 0x70, 0xf8, 0x45, 0xcb, 0x27,
	0x75, 0x9f, 0x5c, 0x6e, 0x04, 0xee, 0x33, 0xf6, 0x9f, 0x7c, 0xf7, 0x0e, 0xa0, 0xf4, 0x76, 0x82,
	0xf6, 0x33, 0xc8, 0x15, 0x0c, 0x96, 0xce, 0x41, 0x21, 0x2c, 0xa3, 0xeb, 0x15, 0xac, 0x70, 0xfb,
	0x03, 0xfa, 0x73, 0xe1, 0xf8, 0x67, 0xc7, 0xb1, 0x9b, 0x07, 0x63, 0x11, 0x74, 0x40, 0xe9, 0x49,
	0x2c, 0x28, 0x29, 0x73, 0x5c, 0xe7, 0xb3, 0xa6, 0x4f, 0x17, 0xf7, 0xe4, 0xa4, 0x15, 0x84, 0xc8,
	0x1c, 0xc7, 0xf9, 0x21, 0x06, 0xa0, 0xf2, 0x3c, 0xa2, 0xdd, 0x1c, 0xa2, 0x43, 0xd7, 0x7f, 0xe5,
	0xe2, 0x18, 0x55, 0x17, 0xa0, 0xb0, 0x71, 0x81, 0xb6, 0x33, 0x19, 0x66, 0x87, 0x80, 0x17, 0x41,
	0x98, 0xd7, 0x4b, 0x50, 0x79, 0x6e, 0x05, 0xa9, 0x0b, 0xef, 0xc6, 0x7c, 0x56, 0x2e, 0x41, 0xe5,
	0x39, 0x15, 0xb8, 0x16, 0xde, 0x4a, 0xb9, 0xae, 0xaf, 0x97, 0xe8, 0xff, 0xc1, 0x7f, 0xbf, 0x07,
	0x00, 0x00, 0xff, 0xff, 0x95, 0x94, 0xdf, 0x47, 0x24, 0x0e, 0x00, 0x00,
}
