// Code generated by SQLBoiler 3.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Department   string
	Employee     string
	EmployeeType string
}{
	Department:   "department",
	Employee:     "employee",
	EmployeeType: "employee_type",
}
