// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/accounts/accounts.proto

package go_micro_srv_accounts

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EmptyMessage struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyMessage) Reset()         { *m = EmptyMessage{} }
func (m *EmptyMessage) String() string { return proto.CompactTextString(m) }
func (*EmptyMessage) ProtoMessage()    {}
func (*EmptyMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_db6715f3b9f60771, []int{0}
}

func (m *EmptyMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyMessage.Unmarshal(m, b)
}
func (m *EmptyMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyMessage.Marshal(b, m, deterministic)
}
func (m *EmptyMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyMessage.Merge(m, src)
}
func (m *EmptyMessage) XXX_Size() int {
	return xxx_messageInfo_EmptyMessage.Size(m)
}
func (m *EmptyMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyMessage.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyMessage proto.InternalMessageInfo

type CreateRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Name                 string   `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Role                 string   `protobuf:"bytes,6,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_db6715f3b9f60771, []int{1}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CreateRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *CreateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateRequest) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

type CreateResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_db6715f3b9f60771, []int{2}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// Login
type LoginRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_db6715f3b9f60771, []int{3}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Role                 string   `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	Token                string   `protobuf:"bytes,6,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_db6715f3b9f60771, []int{4}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginResponse) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *LoginResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LoginResponse) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *LoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

// Update
type UpdateRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,3,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_db6715f3b9f60771, []int{5}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UpdateRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UpdateRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *UpdateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// Disable
type DisableRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisableRequest) Reset()         { *m = DisableRequest{} }
func (m *DisableRequest) String() string { return proto.CompactTextString(m) }
func (*DisableRequest) ProtoMessage()    {}
func (*DisableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_db6715f3b9f60771, []int{6}
}

func (m *DisableRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisableRequest.Unmarshal(m, b)
}
func (m *DisableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisableRequest.Marshal(b, m, deterministic)
}
func (m *DisableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisableRequest.Merge(m, src)
}
func (m *DisableRequest) XXX_Size() int {
	return xxx_messageInfo_DisableRequest.Size(m)
}
func (m *DisableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DisableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DisableRequest proto.InternalMessageInfo

func (m *DisableRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

// List
type ListRequest struct {
	SkipCount            int32    `protobuf:"varint,1,opt,name=skipCount,proto3" json:"skipCount,omitempty"`
	MaxResultCount       int32    `protobuf:"varint,2,opt,name=maxResultCount,proto3" json:"maxResultCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_db6715f3b9f60771, []int{7}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetSkipCount() int32 {
	if m != nil {
		return m.SkipCount
	}
	return 0
}

func (m *ListRequest) GetMaxResultCount() int32 {
	if m != nil {
		return m.MaxResultCount
	}
	return 0
}

type ListResponse struct {
	TotalCount           int32    `protobuf:"varint,1,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	Users                []*User  `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_db6715f3b9f60771, []int{8}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetTotalCount() int32 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func (m *ListResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,4,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	Name                 string   `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Role                 string   `protobuf:"bytes,6,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_db6715f3b9f60771, []int{9}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

// Details
type DetailsRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DetailsRequest) Reset()         { *m = DetailsRequest{} }
func (m *DetailsRequest) String() string { return proto.CompactTextString(m) }
func (*DetailsRequest) ProtoMessage()    {}
func (*DetailsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_db6715f3b9f60771, []int{10}
}

func (m *DetailsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetailsRequest.Unmarshal(m, b)
}
func (m *DetailsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetailsRequest.Marshal(b, m, deterministic)
}
func (m *DetailsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetailsRequest.Merge(m, src)
}
func (m *DetailsRequest) XXX_Size() int {
	return xxx_messageInfo_DetailsRequest.Size(m)
}
func (m *DetailsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DetailsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DetailsRequest proto.InternalMessageInfo

func (m *DetailsRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type DetailsResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DetailsResponse) Reset()         { *m = DetailsResponse{} }
func (m *DetailsResponse) String() string { return proto.CompactTextString(m) }
func (*DetailsResponse) ProtoMessage()    {}
func (*DetailsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_db6715f3b9f60771, []int{11}
}

func (m *DetailsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetailsResponse.Unmarshal(m, b)
}
func (m *DetailsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetailsResponse.Marshal(b, m, deterministic)
}
func (m *DetailsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetailsResponse.Merge(m, src)
}
func (m *DetailsResponse) XXX_Size() int {
	return xxx_messageInfo_DetailsResponse.Size(m)
}
func (m *DetailsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DetailsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DetailsResponse proto.InternalMessageInfo

func (m *DetailsResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

// Password
type PasswordResetTokenRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PasswordResetTokenRequest) Reset()         { *m = PasswordResetTokenRequest{} }
func (m *PasswordResetTokenRequest) String() string { return proto.CompactTextString(m) }
func (*PasswordResetTokenRequest) ProtoMessage()    {}
func (*PasswordResetTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_db6715f3b9f60771, []int{12}
}

func (m *PasswordResetTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PasswordResetTokenRequest.Unmarshal(m, b)
}
func (m *PasswordResetTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PasswordResetTokenRequest.Marshal(b, m, deterministic)
}
func (m *PasswordResetTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PasswordResetTokenRequest.Merge(m, src)
}
func (m *PasswordResetTokenRequest) XXX_Size() int {
	return xxx_messageInfo_PasswordResetTokenRequest.Size(m)
}
func (m *PasswordResetTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PasswordResetTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PasswordResetTokenRequest proto.InternalMessageInfo

func (m *PasswordResetTokenRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type PasswordResetTokenResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PasswordResetTokenResponse) Reset()         { *m = PasswordResetTokenResponse{} }
func (m *PasswordResetTokenResponse) String() string { return proto.CompactTextString(m) }
func (*PasswordResetTokenResponse) ProtoMessage()    {}
func (*PasswordResetTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_db6715f3b9f60771, []int{13}
}

func (m *PasswordResetTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PasswordResetTokenResponse.Unmarshal(m, b)
}
func (m *PasswordResetTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PasswordResetTokenResponse.Marshal(b, m, deterministic)
}
func (m *PasswordResetTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PasswordResetTokenResponse.Merge(m, src)
}
func (m *PasswordResetTokenResponse) XXX_Size() int {
	return xxx_messageInfo_PasswordResetTokenResponse.Size(m)
}
func (m *PasswordResetTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PasswordResetTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PasswordResetTokenResponse proto.InternalMessageInfo

func (m *PasswordResetTokenResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *PasswordResetTokenResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ResetPasswordRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetPasswordRequest) Reset()         { *m = ResetPasswordRequest{} }
func (m *ResetPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ResetPasswordRequest) ProtoMessage()    {}
func (*ResetPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_db6715f3b9f60771, []int{14}
}

func (m *ResetPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetPasswordRequest.Unmarshal(m, b)
}
func (m *ResetPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetPasswordRequest.Marshal(b, m, deterministic)
}
func (m *ResetPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetPasswordRequest.Merge(m, src)
}
func (m *ResetPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ResetPasswordRequest.Size(m)
}
func (m *ResetPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResetPasswordRequest proto.InternalMessageInfo

func (m *ResetPasswordRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ResetPasswordRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ChangePasswordRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	CurrentPassword      string   `protobuf:"bytes,2,opt,name=currentPassword,proto3" json:"currentPassword,omitempty"`
	NewPassword          string   `protobuf:"bytes,3,opt,name=newPassword,proto3" json:"newPassword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangePasswordRequest) Reset()         { *m = ChangePasswordRequest{} }
func (m *ChangePasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ChangePasswordRequest) ProtoMessage()    {}
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_db6715f3b9f60771, []int{15}
}

func (m *ChangePasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePasswordRequest.Unmarshal(m, b)
}
func (m *ChangePasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePasswordRequest.Marshal(b, m, deterministic)
}
func (m *ChangePasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePasswordRequest.Merge(m, src)
}
func (m *ChangePasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ChangePasswordRequest.Size(m)
}
func (m *ChangePasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePasswordRequest proto.InternalMessageInfo

func (m *ChangePasswordRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ChangePasswordRequest) GetCurrentPassword() string {
	if m != nil {
		return m.CurrentPassword
	}
	return ""
}

func (m *ChangePasswordRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

// Role
type AddRoleRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRoleRequest) Reset()         { *m = AddRoleRequest{} }
func (m *AddRoleRequest) String() string { return proto.CompactTextString(m) }
func (*AddRoleRequest) ProtoMessage()    {}
func (*AddRoleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_db6715f3b9f60771, []int{16}
}

func (m *AddRoleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRoleRequest.Unmarshal(m, b)
}
func (m *AddRoleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRoleRequest.Marshal(b, m, deterministic)
}
func (m *AddRoleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRoleRequest.Merge(m, src)
}
func (m *AddRoleRequest) XXX_Size() int {
	return xxx_messageInfo_AddRoleRequest.Size(m)
}
func (m *AddRoleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRoleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRoleRequest proto.InternalMessageInfo

func (m *AddRoleRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type AddRoleResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRoleResponse) Reset()         { *m = AddRoleResponse{} }
func (m *AddRoleResponse) String() string { return proto.CompactTextString(m) }
func (*AddRoleResponse) ProtoMessage()    {}
func (*AddRoleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_db6715f3b9f60771, []int{17}
}

func (m *AddRoleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRoleResponse.Unmarshal(m, b)
}
func (m *AddRoleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRoleResponse.Marshal(b, m, deterministic)
}
func (m *AddRoleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRoleResponse.Merge(m, src)
}
func (m *AddRoleResponse) XXX_Size() int {
	return xxx_messageInfo_AddRoleResponse.Size(m)
}
func (m *AddRoleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRoleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddRoleResponse proto.InternalMessageInfo

func (m *AddRoleResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetRolesResponse struct {
	Roles                []*Role  `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRolesResponse) Reset()         { *m = GetRolesResponse{} }
func (m *GetRolesResponse) String() string { return proto.CompactTextString(m) }
func (*GetRolesResponse) ProtoMessage()    {}
func (*GetRolesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_db6715f3b9f60771, []int{18}
}

func (m *GetRolesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRolesResponse.Unmarshal(m, b)
}
func (m *GetRolesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRolesResponse.Marshal(b, m, deterministic)
}
func (m *GetRolesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRolesResponse.Merge(m, src)
}
func (m *GetRolesResponse) XXX_Size() int {
	return xxx_messageInfo_GetRolesResponse.Size(m)
}
func (m *GetRolesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRolesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRolesResponse proto.InternalMessageInfo

func (m *GetRolesResponse) GetRoles() []*Role {
	if m != nil {
		return m.Roles
	}
	return nil
}

type Role struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Role) Reset()         { *m = Role{} }
func (m *Role) String() string { return proto.CompactTextString(m) }
func (*Role) ProtoMessage()    {}
func (*Role) Descriptor() ([]byte, []int) {
	return fileDescriptor_db6715f3b9f60771, []int{19}
}

func (m *Role) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Role.Unmarshal(m, b)
}
func (m *Role) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Role.Marshal(b, m, deterministic)
}
func (m *Role) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Role.Merge(m, src)
}
func (m *Role) XXX_Size() int {
	return xxx_messageInfo_Role.Size(m)
}
func (m *Role) XXX_DiscardUnknown() {
	xxx_messageInfo_Role.DiscardUnknown(m)
}

var xxx_messageInfo_Role proto.InternalMessageInfo

func (m *Role) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Role) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ChangeRoleRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Role                 string   `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeRoleRequest) Reset()         { *m = ChangeRoleRequest{} }
func (m *ChangeRoleRequest) String() string { return proto.CompactTextString(m) }
func (*ChangeRoleRequest) ProtoMessage()    {}
func (*ChangeRoleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_db6715f3b9f60771, []int{20}
}

func (m *ChangeRoleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeRoleRequest.Unmarshal(m, b)
}
func (m *ChangeRoleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeRoleRequest.Marshal(b, m, deterministic)
}
func (m *ChangeRoleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeRoleRequest.Merge(m, src)
}
func (m *ChangeRoleRequest) XXX_Size() int {
	return xxx_messageInfo_ChangeRoleRequest.Size(m)
}
func (m *ChangeRoleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeRoleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeRoleRequest proto.InternalMessageInfo

func (m *ChangeRoleRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ChangeRoleRequest) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func init() {
	proto.RegisterType((*EmptyMessage)(nil), "go.micro.srv.accounts.EmptyMessage")
	proto.RegisterType((*CreateRequest)(nil), "go.micro.srv.accounts.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "go.micro.srv.accounts.CreateResponse")
	proto.RegisterType((*LoginRequest)(nil), "go.micro.srv.accounts.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "go.micro.srv.accounts.LoginResponse")
	proto.RegisterType((*UpdateRequest)(nil), "go.micro.srv.accounts.UpdateRequest")
	proto.RegisterType((*DisableRequest)(nil), "go.micro.srv.accounts.DisableRequest")
	proto.RegisterType((*ListRequest)(nil), "go.micro.srv.accounts.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "go.micro.srv.accounts.ListResponse")
	proto.RegisterType((*User)(nil), "go.micro.srv.accounts.User")
	proto.RegisterType((*DetailsRequest)(nil), "go.micro.srv.accounts.DetailsRequest")
	proto.RegisterType((*DetailsResponse)(nil), "go.micro.srv.accounts.DetailsResponse")
	proto.RegisterType((*PasswordResetTokenRequest)(nil), "go.micro.srv.accounts.PasswordResetTokenRequest")
	proto.RegisterType((*PasswordResetTokenResponse)(nil), "go.micro.srv.accounts.PasswordResetTokenResponse")
	proto.RegisterType((*ResetPasswordRequest)(nil), "go.micro.srv.accounts.ResetPasswordRequest")
	proto.RegisterType((*ChangePasswordRequest)(nil), "go.micro.srv.accounts.ChangePasswordRequest")
	proto.RegisterType((*AddRoleRequest)(nil), "go.micro.srv.accounts.AddRoleRequest")
	proto.RegisterType((*AddRoleResponse)(nil), "go.micro.srv.accounts.AddRoleResponse")
	proto.RegisterType((*GetRolesResponse)(nil), "go.micro.srv.accounts.GetRolesResponse")
	proto.RegisterType((*Role)(nil), "go.micro.srv.accounts.Role")
	proto.RegisterType((*ChangeRoleRequest)(nil), "go.micro.srv.accounts.ChangeRoleRequest")
}

func init() { proto.RegisterFile("proto/accounts/accounts.proto", fileDescriptor_db6715f3b9f60771) }

var fileDescriptor_db6715f3b9f60771 = []byte{
	// 775 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0x4f, 0x6f, 0xd3, 0x4a,
	0x10, 0x8f, 0x1d, 0x3b, 0x4d, 0xa7, 0x89, 0xfb, 0xde, 0xaa, 0x95, 0xfc, 0xfc, 0xde, 0x43, 0xe9,
	0x52, 0x4a, 0x04, 0x55, 0x4a, 0xcb, 0x81, 0x73, 0x09, 0x05, 0x0e, 0x05, 0x81, 0x69, 0x55, 0x81,
	0x84, 0x90, 0x9b, 0xac, 0x52, 0xab, 0x89, 0x6d, 0xbc, 0x0e, 0x05, 0x71, 0xe0, 0x3b, 0xf0, 0x11,
	0x38, 0xf1, 0x0d, 0xb9, 0xa2, 0x5d, 0xaf, 0xff, 0xa5, 0x5e, 0xd7, 0xa5, 0xb7, 0xec, 0xcc, 0x6f,
	0x67, 0x7e, 0x33, 0x3b, 0xf3, 0x73, 0xe0, 0xff, 0x20, 0xf4, 0x23, 0x7f, 0xc7, 0x19, 0x8d, 0xfc,
	0xb9, 0x17, 0xd1, 0xf4, 0xc7, 0x80, 0xdb, 0xd1, 0xfa, 0xc4, 0x1f, 0xcc, 0xdc, 0x51, 0xe8, 0x0f,
	0x68, 0xf8, 0x69, 0x90, 0x38, 0xb1, 0x01, 0x9d, 0x83, 0x59, 0x10, 0x7d, 0x79, 0x41, 0x28, 0x75,
	0x26, 0x04, 0xff, 0x54, 0xa0, 0x3b, 0x0c, 0x89, 0x13, 0x11, 0x9b, 0x7c, 0x9c, 0x13, 0x1a, 0x21,
	0x0b, 0xda, 0x73, 0x4a, 0x42, 0xcf, 0x99, 0x11, 0x53, 0xe9, 0x29, 0xfd, 0x65, 0x3b, 0x3d, 0x33,
	0x5f, 0xe0, 0x50, 0x7a, 0xe1, 0x87, 0x63, 0x53, 0x8d, 0x7d, 0xc9, 0x19, 0xad, 0x81, 0x4e, 0x66,
	0x8e, 0x3b, 0x35, 0x9b, 0xdc, 0x11, 0x1f, 0xd0, 0x06, 0x74, 0x82, 0x33, 0xdf, 0x23, 0x1f, 0xbc,
	0xf9, 0xec, 0x94, 0x84, 0xa6, 0xc6, 0x9d, 0x2b, 0xdc, 0xf6, 0x92, 0x9b, 0x10, 0x02, 0x8d, 0x27,
	0xd3, 0xb9, 0x8b, 0xff, 0x66, 0xb6, 0xd0, 0x9f, 0x12, 0xb3, 0x15, 0xdb, 0xd8, 0x6f, 0xdc, 0x03,
	0x23, 0x61, 0x4a, 0x03, 0xdf, 0xa3, 0x04, 0x19, 0xa0, 0xba, 0x63, 0x41, 0x52, 0x75, 0xc7, 0xf8,
	0x29, 0x74, 0x0e, 0xfd, 0x89, 0xeb, 0xdd, 0xb0, 0x14, 0xfc, 0x43, 0x81, 0xae, 0x08, 0x24, 0x32,
	0x55, 0x45, 0x4a, 0x0b, 0x57, 0xab, 0x0a, 0x6f, 0xca, 0x0b, 0xd7, 0x4a, 0x0a, 0xd7, 0xb3, 0xc2,
	0x59, 0x82, 0xc8, 0x3f, 0x27, 0x9e, 0xe8, 0x46, 0x7c, 0xc0, 0x17, 0xd0, 0x3d, 0x0e, 0xc6, 0x35,
	0x1f, 0xae, 0x9c, 0x63, 0x0f, 0xf2, 0x7c, 0x6a, 0x52, 0xc4, 0xdb, 0x60, 0x3c, 0x71, 0xa9, 0x73,
	0x3a, 0xad, 0x93, 0x19, 0xbf, 0x81, 0x95, 0x43, 0x97, 0x46, 0x09, 0xf4, 0x3f, 0x58, 0xa6, 0xe7,
	0x6e, 0x30, 0x64, 0xd3, 0xc8, 0xb1, 0xba, 0x9d, 0x19, 0xd0, 0x16, 0x18, 0x33, 0xe7, 0xb3, 0x4d,
	0xe8, 0x7c, 0x1a, 0xc5, 0x10, 0x95, 0x43, 0x16, 0xac, 0xd8, 0x81, 0x4e, 0x1c, 0x54, 0x3c, 0xcf,
	0x2d, 0x80, 0xc8, 0x8f, 0x9c, 0x69, 0x3e, 0x6c, 0xce, 0x82, 0x76, 0x41, 0x67, 0x84, 0xa8, 0xa9,
	0xf6, 0x9a, 0xfd, 0x95, 0xbd, 0x7f, 0x07, 0xa5, 0xcb, 0x31, 0x38, 0xa6, 0x24, 0xb4, 0x63, 0x24,
	0xfe, 0xae, 0x80, 0xc6, 0xce, 0x8b, 0x43, 0x56, 0x28, 0x56, 0x95, 0xb5, 0xb9, 0x59, 0xd1, 0xe6,
	0x1b, 0xac, 0x00, 0x6b, 0x3d, 0x89, 0x1c, 0x77, 0x4a, 0xeb, 0xb4, 0xfe, 0x31, 0xac, 0xa6, 0x68,
	0xd1, 0xa8, 0x1d, 0xd0, 0x98, 0x9b, 0x43, 0xaf, 0xe8, 0x03, 0x07, 0xe2, 0x47, 0xf0, 0xcf, 0x2b,
	0xb1, 0x16, 0x36, 0xa1, 0x24, 0x3a, 0x62, 0xb3, 0x57, 0x27, 0xf9, 0x08, 0xac, 0xb2, 0x8b, 0x7f,
	0xc8, 0x23, 0xdb, 0x01, 0x35, 0xbf, 0x03, 0xcf, 0x61, 0x8d, 0x07, 0xcf, 0x32, 0xd5, 0x5a, 0x85,
	0x92, 0x48, 0xdf, 0x60, 0x7d, 0x78, 0xe6, 0x78, 0x13, 0x72, 0x9d, 0x50, 0x7d, 0x58, 0x1d, 0xcd,
	0xc3, 0x90, 0x78, 0x29, 0x01, 0x11, 0x74, 0xd1, 0xcc, 0x46, 0xc0, 0x23, 0x17, 0x29, 0x4a, 0x6c,
	0x5a, 0xce, 0x84, 0x37, 0xc1, 0xd8, 0x1f, 0x8f, 0x6d, 0x3f, 0xdb, 0xaa, 0x64, 0x28, 0x94, 0xdc,
	0xee, 0x6d, 0xc0, 0x6a, 0x8a, 0x92, 0x88, 0xe0, 0x01, 0xfc, 0xf5, 0x8c, 0x44, 0x0c, 0x92, 0x3d,
	0xfb, 0x2e, 0xe8, 0x6c, 0x7e, 0xa8, 0xa9, 0x54, 0xce, 0x3f, 0x8f, 0x1b, 0x23, 0xf1, 0x3d, 0xd0,
	0xd8, 0xf1, 0xd2, 0xf8, 0x27, 0xac, 0xd4, 0x1c, 0xab, 0x21, 0xfc, 0x1d, 0x37, 0x2f, 0x4f, 0xbf,
	0xaa, 0x71, 0xc9, 0x6c, 0xab, 0xd9, 0x6c, 0xef, 0xfd, 0x6a, 0x43, 0x7b, 0x5f, 0x30, 0x41, 0x27,
	0xd0, 0x8a, 0xb5, 0x1e, 0x6d, 0x4a, 0xb8, 0x16, 0x3e, 0x5a, 0xd6, 0x9d, 0x2b, 0x50, 0x71, 0x1f,
	0x70, 0x03, 0x1d, 0x81, 0xce, 0x95, 0x1d, 0xdd, 0x96, 0xdc, 0xc8, 0x7f, 0x40, 0xac, 0xcd, 0x6a,
	0x50, 0x1a, 0xf5, 0x18, 0x5a, 0xb1, 0x16, 0x4b, 0xe9, 0x16, 0xa4, 0xda, 0x92, 0x25, 0x2f, 0x7c,
	0x9a, 0x1b, 0xe8, 0x04, 0x96, 0x84, 0xd2, 0x22, 0x59, 0x81, 0x45, 0x25, 0xae, 0x1b, 0xf8, 0x35,
	0x68, 0x4c, 0x3f, 0x11, 0x96, 0xd5, 0x97, 0x29, 0xb6, 0x34, 0x64, 0x5e, 0x80, 0x71, 0x03, 0xbd,
	0x83, 0x25, 0x21, 0x36, 0x72, 0xae, 0x05, 0xe9, 0xb2, 0xb6, 0xae, 0x82, 0xa5, 0xb1, 0xbf, 0x02,
	0xba, 0xac, 0x25, 0xe8, 0x81, 0xe4, 0xbe, 0x54, 0xaf, 0xac, 0xdd, 0x6b, 0xdc, 0x48, 0x93, 0x8f,
	0xa0, 0x5b, 0xd0, 0x18, 0x74, 0x5f, 0xb6, 0x3d, 0x25, 0x4a, 0x54, 0xf7, 0x41, 0x08, 0x18, 0x45,
	0xf9, 0x41, 0xdb, 0xb2, 0x89, 0x2e, 0x53, 0xa9, 0xba, 0x69, 0xde, 0xc2, 0x92, 0x90, 0x0f, 0xe9,
	0x23, 0x15, 0x45, 0xc8, 0xaa, 0x07, 0xe3, 0xef, 0xdf, 0x4e, 0x64, 0x07, 0xd5, 0x61, 0x63, 0xdd,
	0x95, 0x80, 0x16, 0xc5, 0x0b, 0x37, 0xd0, 0x7b, 0x80, 0x4c, 0x5f, 0x50, 0xbf, 0xb2, 0x33, 0x79,
	0xf2, 0xf5, 0xba, 0x72, 0xda, 0xe2, 0xff, 0x98, 0x1f, 0xfe, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xe7,
	0x04, 0xf4, 0x9d, 0x52, 0x0b, 0x00, 0x00,
}
