// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/acl/acl.proto

package go_micro_srv_acl

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EmptyMessage struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyMessage) Reset()         { *m = EmptyMessage{} }
func (m *EmptyMessage) String() string { return proto.CompactTextString(m) }
func (*EmptyMessage) ProtoMessage()    {}
func (*EmptyMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_c758efde931a9f1b, []int{0}
}

func (m *EmptyMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyMessage.Unmarshal(m, b)
}
func (m *EmptyMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyMessage.Marshal(b, m, deterministic)
}
func (m *EmptyMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyMessage.Merge(m, src)
}
func (m *EmptyMessage) XXX_Size() int {
	return xxx_messageInfo_EmptyMessage.Size(m)
}
func (m *EmptyMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyMessage.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyMessage proto.InternalMessageInfo

type CreateUserRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Name                 string   `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Role                 string   `protobuf:"bytes,6,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c758efde931a9f1b, []int{1}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CreateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateUserRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *CreateUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateUserRequest) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

type CreateUserResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c758efde931a9f1b, []int{2}
}

func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(m, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// Login
type LoginRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c758efde931a9f1b, []int{3}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Role                 string   `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	Token                string   `protobuf:"bytes,6,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c758efde931a9f1b, []int{4}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginResponse) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *LoginResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LoginResponse) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *LoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

// Update
type UpdateUserRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,3,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c758efde931a9f1b, []int{5}
}

func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(m, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UpdateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UpdateUserRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *UpdateUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// Delete User
type DeleteUserRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserRequest) Reset()         { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()    {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c758efde931a9f1b, []int{6}
}

func (m *DeleteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserRequest.Unmarshal(m, b)
}
func (m *DeleteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserRequest.Marshal(b, m, deterministic)
}
func (m *DeleteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserRequest.Merge(m, src)
}
func (m *DeleteUserRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserRequest.Size(m)
}
func (m *DeleteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserRequest proto.InternalMessageInfo

func (m *DeleteUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

// Disable
type DisableUserRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisableUserRequest) Reset()         { *m = DisableUserRequest{} }
func (m *DisableUserRequest) String() string { return proto.CompactTextString(m) }
func (*DisableUserRequest) ProtoMessage()    {}
func (*DisableUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c758efde931a9f1b, []int{7}
}

func (m *DisableUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisableUserRequest.Unmarshal(m, b)
}
func (m *DisableUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisableUserRequest.Marshal(b, m, deterministic)
}
func (m *DisableUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisableUserRequest.Merge(m, src)
}
func (m *DisableUserRequest) XXX_Size() int {
	return xxx_messageInfo_DisableUserRequest.Size(m)
}
func (m *DisableUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DisableUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DisableUserRequest proto.InternalMessageInfo

func (m *DisableUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

// List
type UsersRequest struct {
	SkipCount            int32    `protobuf:"varint,1,opt,name=skipCount,proto3" json:"skipCount,omitempty"`
	MaxResultCount       int32    `protobuf:"varint,2,opt,name=maxResultCount,proto3" json:"maxResultCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsersRequest) Reset()         { *m = UsersRequest{} }
func (m *UsersRequest) String() string { return proto.CompactTextString(m) }
func (*UsersRequest) ProtoMessage()    {}
func (*UsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c758efde931a9f1b, []int{8}
}

func (m *UsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersRequest.Unmarshal(m, b)
}
func (m *UsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersRequest.Marshal(b, m, deterministic)
}
func (m *UsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersRequest.Merge(m, src)
}
func (m *UsersRequest) XXX_Size() int {
	return xxx_messageInfo_UsersRequest.Size(m)
}
func (m *UsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UsersRequest proto.InternalMessageInfo

func (m *UsersRequest) GetSkipCount() int32 {
	if m != nil {
		return m.SkipCount
	}
	return 0
}

func (m *UsersRequest) GetMaxResultCount() int32 {
	if m != nil {
		return m.MaxResultCount
	}
	return 0
}

type UsersResponse struct {
	TotalCount           int32    `protobuf:"varint,1,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	Users                []*User  `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsersResponse) Reset()         { *m = UsersResponse{} }
func (m *UsersResponse) String() string { return proto.CompactTextString(m) }
func (*UsersResponse) ProtoMessage()    {}
func (*UsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c758efde931a9f1b, []int{9}
}

func (m *UsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersResponse.Unmarshal(m, b)
}
func (m *UsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersResponse.Marshal(b, m, deterministic)
}
func (m *UsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersResponse.Merge(m, src)
}
func (m *UsersResponse) XXX_Size() int {
	return xxx_messageInfo_UsersResponse.Size(m)
}
func (m *UsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UsersResponse proto.InternalMessageInfo

func (m *UsersResponse) GetTotalCount() int32 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func (m *UsersResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,4,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	Name                 string   `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Role                 string   `protobuf:"bytes,6,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_c758efde931a9f1b, []int{10}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

// Details
type UserDetailsRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserDetailsRequest) Reset()         { *m = UserDetailsRequest{} }
func (m *UserDetailsRequest) String() string { return proto.CompactTextString(m) }
func (*UserDetailsRequest) ProtoMessage()    {}
func (*UserDetailsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c758efde931a9f1b, []int{11}
}

func (m *UserDetailsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserDetailsRequest.Unmarshal(m, b)
}
func (m *UserDetailsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserDetailsRequest.Marshal(b, m, deterministic)
}
func (m *UserDetailsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserDetailsRequest.Merge(m, src)
}
func (m *UserDetailsRequest) XXX_Size() int {
	return xxx_messageInfo_UserDetailsRequest.Size(m)
}
func (m *UserDetailsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserDetailsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserDetailsRequest proto.InternalMessageInfo

func (m *UserDetailsRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type UserDetailsResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserDetailsResponse) Reset()         { *m = UserDetailsResponse{} }
func (m *UserDetailsResponse) String() string { return proto.CompactTextString(m) }
func (*UserDetailsResponse) ProtoMessage()    {}
func (*UserDetailsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c758efde931a9f1b, []int{12}
}

func (m *UserDetailsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserDetailsResponse.Unmarshal(m, b)
}
func (m *UserDetailsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserDetailsResponse.Marshal(b, m, deterministic)
}
func (m *UserDetailsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserDetailsResponse.Merge(m, src)
}
func (m *UserDetailsResponse) XXX_Size() int {
	return xxx_messageInfo_UserDetailsResponse.Size(m)
}
func (m *UserDetailsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserDetailsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserDetailsResponse proto.InternalMessageInfo

func (m *UserDetailsResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

// Password
type PasswordResetTokenRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PasswordResetTokenRequest) Reset()         { *m = PasswordResetTokenRequest{} }
func (m *PasswordResetTokenRequest) String() string { return proto.CompactTextString(m) }
func (*PasswordResetTokenRequest) ProtoMessage()    {}
func (*PasswordResetTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c758efde931a9f1b, []int{13}
}

func (m *PasswordResetTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PasswordResetTokenRequest.Unmarshal(m, b)
}
func (m *PasswordResetTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PasswordResetTokenRequest.Marshal(b, m, deterministic)
}
func (m *PasswordResetTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PasswordResetTokenRequest.Merge(m, src)
}
func (m *PasswordResetTokenRequest) XXX_Size() int {
	return xxx_messageInfo_PasswordResetTokenRequest.Size(m)
}
func (m *PasswordResetTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PasswordResetTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PasswordResetTokenRequest proto.InternalMessageInfo

func (m *PasswordResetTokenRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type PasswordResetTokenResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PasswordResetTokenResponse) Reset()         { *m = PasswordResetTokenResponse{} }
func (m *PasswordResetTokenResponse) String() string { return proto.CompactTextString(m) }
func (*PasswordResetTokenResponse) ProtoMessage()    {}
func (*PasswordResetTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c758efde931a9f1b, []int{14}
}

func (m *PasswordResetTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PasswordResetTokenResponse.Unmarshal(m, b)
}
func (m *PasswordResetTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PasswordResetTokenResponse.Marshal(b, m, deterministic)
}
func (m *PasswordResetTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PasswordResetTokenResponse.Merge(m, src)
}
func (m *PasswordResetTokenResponse) XXX_Size() int {
	return xxx_messageInfo_PasswordResetTokenResponse.Size(m)
}
func (m *PasswordResetTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PasswordResetTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PasswordResetTokenResponse proto.InternalMessageInfo

func (m *PasswordResetTokenResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *PasswordResetTokenResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ResetPasswordRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetPasswordRequest) Reset()         { *m = ResetPasswordRequest{} }
func (m *ResetPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ResetPasswordRequest) ProtoMessage()    {}
func (*ResetPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c758efde931a9f1b, []int{15}
}

func (m *ResetPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetPasswordRequest.Unmarshal(m, b)
}
func (m *ResetPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetPasswordRequest.Marshal(b, m, deterministic)
}
func (m *ResetPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetPasswordRequest.Merge(m, src)
}
func (m *ResetPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ResetPasswordRequest.Size(m)
}
func (m *ResetPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResetPasswordRequest proto.InternalMessageInfo

func (m *ResetPasswordRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ResetPasswordRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ChangePasswordRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	CurrentPassword      string   `protobuf:"bytes,2,opt,name=currentPassword,proto3" json:"currentPassword,omitempty"`
	NewPassword          string   `protobuf:"bytes,3,opt,name=newPassword,proto3" json:"newPassword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangePasswordRequest) Reset()         { *m = ChangePasswordRequest{} }
func (m *ChangePasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ChangePasswordRequest) ProtoMessage()    {}
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c758efde931a9f1b, []int{16}
}

func (m *ChangePasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePasswordRequest.Unmarshal(m, b)
}
func (m *ChangePasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePasswordRequest.Marshal(b, m, deterministic)
}
func (m *ChangePasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePasswordRequest.Merge(m, src)
}
func (m *ChangePasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ChangePasswordRequest.Size(m)
}
func (m *ChangePasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePasswordRequest proto.InternalMessageInfo

func (m *ChangePasswordRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ChangePasswordRequest) GetCurrentPassword() string {
	if m != nil {
		return m.CurrentPassword
	}
	return ""
}

func (m *ChangePasswordRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

// Role
type AddRoleRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRoleRequest) Reset()         { *m = AddRoleRequest{} }
func (m *AddRoleRequest) String() string { return proto.CompactTextString(m) }
func (*AddRoleRequest) ProtoMessage()    {}
func (*AddRoleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c758efde931a9f1b, []int{17}
}

func (m *AddRoleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRoleRequest.Unmarshal(m, b)
}
func (m *AddRoleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRoleRequest.Marshal(b, m, deterministic)
}
func (m *AddRoleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRoleRequest.Merge(m, src)
}
func (m *AddRoleRequest) XXX_Size() int {
	return xxx_messageInfo_AddRoleRequest.Size(m)
}
func (m *AddRoleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRoleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRoleRequest proto.InternalMessageInfo

func (m *AddRoleRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type AddRoleResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRoleResponse) Reset()         { *m = AddRoleResponse{} }
func (m *AddRoleResponse) String() string { return proto.CompactTextString(m) }
func (*AddRoleResponse) ProtoMessage()    {}
func (*AddRoleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c758efde931a9f1b, []int{18}
}

func (m *AddRoleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRoleResponse.Unmarshal(m, b)
}
func (m *AddRoleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRoleResponse.Marshal(b, m, deterministic)
}
func (m *AddRoleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRoleResponse.Merge(m, src)
}
func (m *AddRoleResponse) XXX_Size() int {
	return xxx_messageInfo_AddRoleResponse.Size(m)
}
func (m *AddRoleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRoleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddRoleResponse proto.InternalMessageInfo

func (m *AddRoleResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetRolesResponse struct {
	Roles                []*Role  `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRolesResponse) Reset()         { *m = GetRolesResponse{} }
func (m *GetRolesResponse) String() string { return proto.CompactTextString(m) }
func (*GetRolesResponse) ProtoMessage()    {}
func (*GetRolesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c758efde931a9f1b, []int{19}
}

func (m *GetRolesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRolesResponse.Unmarshal(m, b)
}
func (m *GetRolesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRolesResponse.Marshal(b, m, deterministic)
}
func (m *GetRolesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRolesResponse.Merge(m, src)
}
func (m *GetRolesResponse) XXX_Size() int {
	return xxx_messageInfo_GetRolesResponse.Size(m)
}
func (m *GetRolesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRolesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRolesResponse proto.InternalMessageInfo

func (m *GetRolesResponse) GetRoles() []*Role {
	if m != nil {
		return m.Roles
	}
	return nil
}

type Role struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Role) Reset()         { *m = Role{} }
func (m *Role) String() string { return proto.CompactTextString(m) }
func (*Role) ProtoMessage()    {}
func (*Role) Descriptor() ([]byte, []int) {
	return fileDescriptor_c758efde931a9f1b, []int{20}
}

func (m *Role) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Role.Unmarshal(m, b)
}
func (m *Role) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Role.Marshal(b, m, deterministic)
}
func (m *Role) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Role.Merge(m, src)
}
func (m *Role) XXX_Size() int {
	return xxx_messageInfo_Role.Size(m)
}
func (m *Role) XXX_DiscardUnknown() {
	xxx_messageInfo_Role.DiscardUnknown(m)
}

var xxx_messageInfo_Role proto.InternalMessageInfo

func (m *Role) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Role) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ChangeRoleRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Role                 string   `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeRoleRequest) Reset()         { *m = ChangeRoleRequest{} }
func (m *ChangeRoleRequest) String() string { return proto.CompactTextString(m) }
func (*ChangeRoleRequest) ProtoMessage()    {}
func (*ChangeRoleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c758efde931a9f1b, []int{21}
}

func (m *ChangeRoleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeRoleRequest.Unmarshal(m, b)
}
func (m *ChangeRoleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeRoleRequest.Marshal(b, m, deterministic)
}
func (m *ChangeRoleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeRoleRequest.Merge(m, src)
}
func (m *ChangeRoleRequest) XXX_Size() int {
	return xxx_messageInfo_ChangeRoleRequest.Size(m)
}
func (m *ChangeRoleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeRoleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeRoleRequest proto.InternalMessageInfo

func (m *ChangeRoleRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ChangeRoleRequest) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func init() {
	proto.RegisterType((*EmptyMessage)(nil), "go.micro.srv.acl.EmptyMessage")
	proto.RegisterType((*CreateUserRequest)(nil), "go.micro.srv.acl.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "go.micro.srv.acl.CreateUserResponse")
	proto.RegisterType((*LoginRequest)(nil), "go.micro.srv.acl.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "go.micro.srv.acl.LoginResponse")
	proto.RegisterType((*UpdateUserRequest)(nil), "go.micro.srv.acl.UpdateUserRequest")
	proto.RegisterType((*DeleteUserRequest)(nil), "go.micro.srv.acl.DeleteUserRequest")
	proto.RegisterType((*DisableUserRequest)(nil), "go.micro.srv.acl.DisableUserRequest")
	proto.RegisterType((*UsersRequest)(nil), "go.micro.srv.acl.UsersRequest")
	proto.RegisterType((*UsersResponse)(nil), "go.micro.srv.acl.UsersResponse")
	proto.RegisterType((*User)(nil), "go.micro.srv.acl.User")
	proto.RegisterType((*UserDetailsRequest)(nil), "go.micro.srv.acl.UserDetailsRequest")
	proto.RegisterType((*UserDetailsResponse)(nil), "go.micro.srv.acl.UserDetailsResponse")
	proto.RegisterType((*PasswordResetTokenRequest)(nil), "go.micro.srv.acl.PasswordResetTokenRequest")
	proto.RegisterType((*PasswordResetTokenResponse)(nil), "go.micro.srv.acl.PasswordResetTokenResponse")
	proto.RegisterType((*ResetPasswordRequest)(nil), "go.micro.srv.acl.ResetPasswordRequest")
	proto.RegisterType((*ChangePasswordRequest)(nil), "go.micro.srv.acl.ChangePasswordRequest")
	proto.RegisterType((*AddRoleRequest)(nil), "go.micro.srv.acl.AddRoleRequest")
	proto.RegisterType((*AddRoleResponse)(nil), "go.micro.srv.acl.AddRoleResponse")
	proto.RegisterType((*GetRolesResponse)(nil), "go.micro.srv.acl.GetRolesResponse")
	proto.RegisterType((*Role)(nil), "go.micro.srv.acl.Role")
	proto.RegisterType((*ChangeRoleRequest)(nil), "go.micro.srv.acl.ChangeRoleRequest")
}

func init() { proto.RegisterFile("proto/acl/acl.proto", fileDescriptor_c758efde931a9f1b) }

var fileDescriptor_c758efde931a9f1b = []byte{
	// 792 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xcb, 0x4e, 0xdb, 0x4c,
	0x14, 0xc6, 0x4e, 0xcc, 0x0f, 0x27, 0x21, 0x90, 0x81, 0xbf, 0x72, 0xad, 0x8a, 0x86, 0x29, 0xa5,
	0x88, 0xa2, 0x80, 0xe8, 0xa2, 0xdb, 0xa2, 0xd0, 0x8b, 0x50, 0x2f, 0x28, 0x85, 0x05, 0xea, 0x4d,
	0x26, 0x19, 0x05, 0x0b, 0xc7, 0x36, 0x1e, 0xa7, 0xb4, 0xea, 0xa2, 0xef, 0xd0, 0x47, 0xe8, 0xba,
	0x4f, 0xd8, 0x55, 0x35, 0xe3, 0xdb, 0x38, 0x1e, 0x27, 0x8e, 0x58, 0x44, 0xf2, 0x9c, 0xf9, 0xe6,
	0x3b, 0x97, 0x39, 0xe7, 0x9b, 0xc0, 0xaa, 0xe7, 0xbb, 0x81, 0xbb, 0x67, 0xf6, 0x6c, 0xf6, 0x6b,
	0xf3, 0x15, 0x5a, 0x19, 0xb8, 0xed, 0xa1, 0xd5, 0xf3, 0xdd, 0x36, 0xf5, 0xbf, 0xb6, 0xcd, 0x9e,
	0x8d, 0x1b, 0x50, 0x7f, 0x3e, 0xf4, 0x82, 0xef, 0x6f, 0x08, 0xa5, 0xe6, 0x80, 0xe0, 0x3f, 0x0a,
	0x34, 0x3b, 0x3e, 0x31, 0x03, 0x72, 0x46, 0x89, 0xdf, 0x25, 0xd7, 0x23, 0x42, 0x03, 0x64, 0xc0,
	0xc2, 0x88, 0x12, 0xdf, 0x31, 0x87, 0x44, 0x57, 0x5a, 0xca, 0xf6, 0x62, 0x37, 0x59, 0xb3, 0x3d,
	0xcf, 0xa4, 0xf4, 0xc6, 0xf5, 0xfb, 0xba, 0x1a, 0xee, 0xc5, 0x6b, 0xb4, 0x06, 0x1a, 0x19, 0x9a,
	0x96, 0xad, 0x57, 0xf8, 0x46, 0xb8, 0x40, 0x1b, 0x50, 0xf7, 0x2e, 0x5d, 0x87, 0x7c, 0x71, 0x46,
	0xc3, 0x0b, 0xe2, 0xeb, 0x55, 0xbe, 0x59, 0xe3, 0xb6, 0xb7, 0xdc, 0x84, 0x10, 0x54, 0xb9, 0x33,
	0x8d, 0x6f, 0xf1, 0x6f, 0x66, 0xf3, 0x5d, 0x9b, 0xe8, 0xf3, 0xa1, 0x8d, 0x7d, 0xe3, 0x4d, 0x40,
	0x62, 0xb4, 0xd4, 0x73, 0x1d, 0x4a, 0x50, 0x03, 0x54, 0xab, 0x1f, 0x05, 0xaa, 0x5a, 0x7d, 0xfc,
	0x02, 0xea, 0xaf, 0xdd, 0x81, 0xe5, 0xdc, 0x32, 0x1d, 0xfc, 0x5b, 0x81, 0xa5, 0x88, 0x28, 0xf2,
	0x34, 0x89, 0x29, 0x49, 0x5e, 0x9d, 0x94, 0x7c, 0xa5, 0x38, 0xf9, 0xaa, 0x24, 0x79, 0x2d, 0x4d,
	0x9e, 0x39, 0x08, 0xdc, 0x2b, 0xe2, 0x44, 0x15, 0x09, 0x17, 0xf8, 0x07, 0x34, 0xcf, 0xbc, 0xfe,
	0x0c, 0x17, 0x28, 0x8f, 0xb3, 0x05, 0x62, 0x4c, 0x25, 0xc3, 0xc4, 0x7b, 0xd0, 0x3c, 0x22, 0x36,
	0x29, 0xed, 0x1c, 0xef, 0x03, 0x3a, 0xb2, 0xa8, 0x79, 0x61, 0x97, 0x3e, 0x71, 0x0a, 0x75, 0x06,
	0xa5, 0x31, 0xf6, 0x1e, 0x2c, 0xd2, 0x2b, 0xcb, 0xeb, 0xb8, 0x23, 0x27, 0xe0, 0x60, 0xad, 0x9b,
	0x1a, 0xd0, 0x16, 0x34, 0x86, 0xe6, 0xb7, 0x2e, 0xa1, 0x23, 0x3b, 0x08, 0x21, 0x2a, 0x87, 0x8c,
	0x59, 0xf1, 0x27, 0x58, 0x8a, 0x58, 0xa3, 0x9b, 0x5d, 0x07, 0x08, 0xdc, 0xc0, 0xb4, 0x45, 0x5e,
	0xc1, 0x82, 0x76, 0x41, 0x63, 0x21, 0x51, 0x5d, 0x6d, 0x55, 0xb6, 0x6b, 0x07, 0x77, 0xda, 0xe3,
	0xa3, 0xd5, 0xe6, 0x09, 0x85, 0x20, 0xfc, 0x4b, 0x81, 0x2a, 0x5b, 0x8f, 0xb7, 0x66, 0x26, 0x53,
	0xb5, 0xe8, 0x62, 0x2a, 0x13, 0x2e, 0xe6, 0x16, 0xc3, 0xb3, 0x0f, 0x88, 0xc5, 0x74, 0x44, 0x02,
	0xd3, 0xb2, 0x69, 0x99, 0xda, 0x1f, 0xc2, 0x6a, 0xe6, 0x44, 0x54, 0xab, 0x1d, 0xa8, 0x32, 0x08,
	0x87, 0x17, 0x97, 0x82, 0x63, 0xf0, 0x53, 0xb8, 0x7b, 0x12, 0xcd, 0x53, 0x97, 0x50, 0x12, 0x9c,
	0xb2, 0xa6, 0x2d, 0xe3, 0xfb, 0x33, 0x18, 0xb2, 0x83, 0xb3, 0x87, 0x90, 0xce, 0x8d, 0x2a, 0xce,
	0xcd, 0x2b, 0x58, 0xe3, 0xbc, 0xa9, 0x93, 0x52, 0xa3, 0x23, 0x61, 0xfa, 0x09, 0xff, 0x77, 0x2e,
	0x4d, 0x67, 0x40, 0x66, 0xa1, 0xda, 0x86, 0xe5, 0xde, 0xc8, 0xf7, 0x89, 0x93, 0x04, 0x10, 0x91,
	0x8e, 0x9b, 0x59, 0x03, 0x38, 0xe4, 0x26, 0x41, 0x45, 0x93, 0x29, 0x98, 0xf0, 0x26, 0x34, 0x0e,
	0xfb, 0xfd, 0xae, 0x6b, 0x93, 0xd8, 0x73, 0xdc, 0x12, 0x8a, 0x30, 0xab, 0x1b, 0xb0, 0x9c, 0xa0,
	0x0a, 0x84, 0xf3, 0x19, 0xac, 0xbc, 0x24, 0x01, 0x83, 0xa4, 0x97, 0xbd, 0x0b, 0x1a, 0xeb, 0x1e,
	0xaa, 0x2b, 0x45, 0x8d, 0xcf, 0x29, 0x43, 0x10, 0xde, 0x81, 0x2a, 0x5b, 0xe6, 0xfa, 0x3e, 0x0e,
	0x48, 0x15, 0x02, 0xea, 0x40, 0x33, 0xac, 0x9b, 0x18, 0xf9, 0xa4, 0x9a, 0xc5, 0x4d, 0xad, 0xa6,
	0x4d, 0x7d, 0xf0, 0x77, 0x01, 0x2a, 0x87, 0x3d, 0x1b, 0x9d, 0x03, 0xa4, 0x2f, 0x03, 0x7a, 0x90,
	0x8f, 0x32, 0xf7, 0xca, 0x19, 0x9b, 0x93, 0x41, 0x61, 0xfe, 0x78, 0x0e, 0x1d, 0x83, 0xc6, 0x5f,
	0x01, 0xb4, 0x9e, 0x3f, 0x20, 0xbe, 0x33, 0xc6, 0xfd, 0xc2, 0xfd, 0x84, 0xeb, 0x3d, 0x40, 0xaa,
	0xd6, 0xb2, 0x30, 0x73, 0x5a, 0x6e, 0x48, 0xbc, 0x66, 0x9e, 0x70, 0x4e, 0x9a, 0xaa, 0xb0, 0x8c,
	0x34, 0xa7, 0xd1, 0x25, 0x48, 0xcf, 0xa0, 0x26, 0x28, 0x35, 0x92, 0x14, 0x2b, 0x2f, 0xe4, 0x25,
	0x68, 0x8f, 0x41, 0xe3, 0xc2, 0x2b, 0x2b, 0xa6, 0xa8, 0xf3, 0xb2, 0x62, 0x66, 0x14, 0x1b, 0xcf,
	0xa1, 0x8f, 0x50, 0x13, 0xe4, 0x49, 0x16, 0x62, 0x5e, 0xef, 0x8c, 0x87, 0x53, 0x50, 0x09, 0xfb,
	0x35, 0xa0, 0xbc, 0x00, 0xa1, 0xc7, 0xf9, 0xe3, 0x85, 0xfa, 0x66, 0xec, 0x96, 0x03, 0x27, 0x2e,
	0xcf, 0x61, 0x29, 0xa3, 0x49, 0x68, 0x4b, 0x32, 0x6d, 0x12, 0xd1, 0x2a, 0x51, 0xf7, 0x0f, 0xd0,
	0xc8, 0x8a, 0x14, 0x7a, 0x24, 0x69, 0x7f, 0x99, 0x8c, 0x95, 0x20, 0x7f, 0x07, 0xff, 0x45, 0xd2,
	0x82, 0x5a, 0x79, 0x70, 0x56, 0x9b, 0x8c, 0xa9, 0x08, 0x3c, 0x87, 0x4e, 0x60, 0x21, 0x16, 0x22,
	0x34, 0xc5, 0xbd, 0x81, 0xf3, 0xfb, 0xe3, 0x22, 0x16, 0xce, 0x48, 0x2a, 0x36, 0x52, 0x7d, 0x18,
	0x97, 0xa2, 0xe9, 0x79, 0x5f, 0xcc, 0xf3, 0xbf, 0xd9, 0x4f, 0xfe, 0x05, 0x00, 0x00, 0xff, 0xff,
	0x84, 0xaa, 0x34, 0x55, 0x7d, 0x0b, 0x00, 0x00,
}
