// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/acl/acl.proto

package go_micro_srv_acl

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Acl service

type AclService interface {
	Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...client.CallOption) (*LoginResponse, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...client.CallOption) (*EmptyMessage, error)
	Disable(ctx context.Context, in *DisableRequest, opts ...client.CallOption) (*EmptyMessage, error)
	List(ctx context.Context, in *ListRequest, opts ...client.CallOption) (*ListResponse, error)
	Details(ctx context.Context, in *DetailsRequest, opts ...client.CallOption) (*DetailsResponse, error)
	PasswordResetToken(ctx context.Context, in *PasswordResetTokenRequest, opts ...client.CallOption) (*PasswordResetTokenResponse, error)
	ResetPassword(ctx context.Context, in *ResetPasswordRequest, opts ...client.CallOption) (*EmptyMessage, error)
	ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...client.CallOption) (*EmptyMessage, error)
	AddRole(ctx context.Context, in *AddRoleRequest, opts ...client.CallOption) (*AddRoleRequest, error)
	GetRoles(ctx context.Context, in *EmptyMessage, opts ...client.CallOption) (*GetRolesResponse, error)
	ChangeRole(ctx context.Context, in *ChangeRoleRequest, opts ...client.CallOption) (*EmptyMessage, error)
}

type aclService struct {
	c    client.Client
	name string
}

func NewAclService(name string, c client.Client) AclService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.srv.acl"
	}
	return &aclService{
		c:    c,
		name: name,
	}
}

func (c *aclService) Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error) {
	req := c.c.NewRequest(c.name, "Acl.Create", in)
	out := new(CreateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aclService) Login(ctx context.Context, in *LoginRequest, opts ...client.CallOption) (*LoginResponse, error) {
	req := c.c.NewRequest(c.name, "Acl.Login", in)
	out := new(LoginResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aclService) Update(ctx context.Context, in *UpdateRequest, opts ...client.CallOption) (*EmptyMessage, error) {
	req := c.c.NewRequest(c.name, "Acl.Update", in)
	out := new(EmptyMessage)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aclService) Disable(ctx context.Context, in *DisableRequest, opts ...client.CallOption) (*EmptyMessage, error) {
	req := c.c.NewRequest(c.name, "Acl.Disable", in)
	out := new(EmptyMessage)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aclService) List(ctx context.Context, in *ListRequest, opts ...client.CallOption) (*ListResponse, error) {
	req := c.c.NewRequest(c.name, "Acl.List", in)
	out := new(ListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aclService) Details(ctx context.Context, in *DetailsRequest, opts ...client.CallOption) (*DetailsResponse, error) {
	req := c.c.NewRequest(c.name, "Acl.Details", in)
	out := new(DetailsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aclService) PasswordResetToken(ctx context.Context, in *PasswordResetTokenRequest, opts ...client.CallOption) (*PasswordResetTokenResponse, error) {
	req := c.c.NewRequest(c.name, "Acl.PasswordResetToken", in)
	out := new(PasswordResetTokenResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aclService) ResetPassword(ctx context.Context, in *ResetPasswordRequest, opts ...client.CallOption) (*EmptyMessage, error) {
	req := c.c.NewRequest(c.name, "Acl.ResetPassword", in)
	out := new(EmptyMessage)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aclService) ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...client.CallOption) (*EmptyMessage, error) {
	req := c.c.NewRequest(c.name, "Acl.ChangePassword", in)
	out := new(EmptyMessage)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aclService) AddRole(ctx context.Context, in *AddRoleRequest, opts ...client.CallOption) (*AddRoleRequest, error) {
	req := c.c.NewRequest(c.name, "Acl.AddRole", in)
	out := new(AddRoleRequest)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aclService) GetRoles(ctx context.Context, in *EmptyMessage, opts ...client.CallOption) (*GetRolesResponse, error) {
	req := c.c.NewRequest(c.name, "Acl.GetRoles", in)
	out := new(GetRolesResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aclService) ChangeRole(ctx context.Context, in *ChangeRoleRequest, opts ...client.CallOption) (*EmptyMessage, error) {
	req := c.c.NewRequest(c.name, "Acl.ChangeRole", in)
	out := new(EmptyMessage)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Acl service

type AclHandler interface {
	Create(context.Context, *CreateRequest, *CreateResponse) error
	Login(context.Context, *LoginRequest, *LoginResponse) error
	Update(context.Context, *UpdateRequest, *EmptyMessage) error
	Disable(context.Context, *DisableRequest, *EmptyMessage) error
	List(context.Context, *ListRequest, *ListResponse) error
	Details(context.Context, *DetailsRequest, *DetailsResponse) error
	PasswordResetToken(context.Context, *PasswordResetTokenRequest, *PasswordResetTokenResponse) error
	ResetPassword(context.Context, *ResetPasswordRequest, *EmptyMessage) error
	ChangePassword(context.Context, *ChangePasswordRequest, *EmptyMessage) error
	AddRole(context.Context, *AddRoleRequest, *AddRoleRequest) error
	GetRoles(context.Context, *EmptyMessage, *GetRolesResponse) error
	ChangeRole(context.Context, *ChangeRoleRequest, *EmptyMessage) error
}

func RegisterAclHandler(s server.Server, hdlr AclHandler, opts ...server.HandlerOption) error {
	type acl interface {
		Create(ctx context.Context, in *CreateRequest, out *CreateResponse) error
		Login(ctx context.Context, in *LoginRequest, out *LoginResponse) error
		Update(ctx context.Context, in *UpdateRequest, out *EmptyMessage) error
		Disable(ctx context.Context, in *DisableRequest, out *EmptyMessage) error
		List(ctx context.Context, in *ListRequest, out *ListResponse) error
		Details(ctx context.Context, in *DetailsRequest, out *DetailsResponse) error
		PasswordResetToken(ctx context.Context, in *PasswordResetTokenRequest, out *PasswordResetTokenResponse) error
		ResetPassword(ctx context.Context, in *ResetPasswordRequest, out *EmptyMessage) error
		ChangePassword(ctx context.Context, in *ChangePasswordRequest, out *EmptyMessage) error
		AddRole(ctx context.Context, in *AddRoleRequest, out *AddRoleRequest) error
		GetRoles(ctx context.Context, in *EmptyMessage, out *GetRolesResponse) error
		ChangeRole(ctx context.Context, in *ChangeRoleRequest, out *EmptyMessage) error
	}
	type Acl struct {
		acl
	}
	h := &aclHandler{hdlr}
	return s.Handle(s.NewHandler(&Acl{h}, opts...))
}

type aclHandler struct {
	AclHandler
}

func (h *aclHandler) Create(ctx context.Context, in *CreateRequest, out *CreateResponse) error {
	return h.AclHandler.Create(ctx, in, out)
}

func (h *aclHandler) Login(ctx context.Context, in *LoginRequest, out *LoginResponse) error {
	return h.AclHandler.Login(ctx, in, out)
}

func (h *aclHandler) Update(ctx context.Context, in *UpdateRequest, out *EmptyMessage) error {
	return h.AclHandler.Update(ctx, in, out)
}

func (h *aclHandler) Disable(ctx context.Context, in *DisableRequest, out *EmptyMessage) error {
	return h.AclHandler.Disable(ctx, in, out)
}

func (h *aclHandler) List(ctx context.Context, in *ListRequest, out *ListResponse) error {
	return h.AclHandler.List(ctx, in, out)
}

func (h *aclHandler) Details(ctx context.Context, in *DetailsRequest, out *DetailsResponse) error {
	return h.AclHandler.Details(ctx, in, out)
}

func (h *aclHandler) PasswordResetToken(ctx context.Context, in *PasswordResetTokenRequest, out *PasswordResetTokenResponse) error {
	return h.AclHandler.PasswordResetToken(ctx, in, out)
}

func (h *aclHandler) ResetPassword(ctx context.Context, in *ResetPasswordRequest, out *EmptyMessage) error {
	return h.AclHandler.ResetPassword(ctx, in, out)
}

func (h *aclHandler) ChangePassword(ctx context.Context, in *ChangePasswordRequest, out *EmptyMessage) error {
	return h.AclHandler.ChangePassword(ctx, in, out)
}

func (h *aclHandler) AddRole(ctx context.Context, in *AddRoleRequest, out *AddRoleRequest) error {
	return h.AclHandler.AddRole(ctx, in, out)
}

func (h *aclHandler) GetRoles(ctx context.Context, in *EmptyMessage, out *GetRolesResponse) error {
	return h.AclHandler.GetRoles(ctx, in, out)
}

func (h *aclHandler) ChangeRole(ctx context.Context, in *ChangeRoleRequest, out *EmptyMessage) error {
	return h.AclHandler.ChangeRole(ctx, in, out)
}
