[psql]
    dbname = "dcrextdata"
    host = "localhost"
    user = "user"
    pass = "pass"
    sslmode = "disable"
    whitelist=["exchange", 
            "exchange_tick",
            "vsp",
            "vsp_tick",
            "pow_data",
            "mempool",
            "block",
            "comm_stat"]
